"use strict";
let lname;
lname = 'kumar';
console.log(lname.toUpperCase());
let age;
age = 20;
let dob = '25';
let result = parseInt(dob);
console.log(result);
let invalid;
invalid = false;
console.log(invalid);
let emplist;
let deplist;
let numlist;
deplist = ['raj', 'kumar'];
numlist = [1, 2, 3];
let results = numlist.filter((num) => num > 2);
console.log(results);
let c = 2 /* Color.Blue */;
